// frontend/pages/login.vue
<template>
  <div>
    <div class="bg-[#2d1a64] flex justify-center items-center h-screen">
      <!-- Left: Image -->
      <div class="w-1/2 h-screen hidden lg:block">
        <img
          src="https://placehold.co/800x/667fff/ffffff.png?text=Your+Image&font=Montserrat"
          alt="Placeholder Image"
          class="object-cover w-full h-full"
        />
      </div>
      <!-- Right: Login Form -->
      <div class="lg:p-36 md:p-52 sm:20 p-8 w-full lg:w-1/2 text-white">
        <h1 class="text-2xl font-semibold mb-4">Login</h1>
        <form action="#" method="POST">
          <!-- Username Input -->
          <div class="mb-4">
            <label for="username" class="block text-white">Username</label>
            <input
              type="text"
              id="username"
              name="username"
              class="w-full border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:border-blue-500 text-black"
              autocomplete="off"
            />
          </div>
          <!-- Password Input -->
          <div class="mb-4">
            <label for="password" class="block text-white">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              class="w-full border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:border-blue-500 text-black"
              autocomplete="off"
            />
          </div>
          <!-- Login Button -->
          <button
            type="submit"
            class="bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-md py-2 px-4 w-full"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

// my-app/src/routes/login/+page.svelte
<script>
    import { goto } from '$app/navigation'; // นำเข้า goto สำหรับการนำทาง
    function handleSubmit() {
      goto(`/swap`);
    }
  </script>
<div class="bg-[#2d1a64] flex justify-center items-center h-screen">
    <!-- Left: Image -->
    <div class="w-1/2 h-screen">
      <img
        src="https://placehold.co/800x/667fff/ffffff.png?text=Your+Image&font=Montserrat"
        alt=""
        class="object-cover w-full h-full"
      />
    </div>
    <!-- Right: Login Form -->
    <div class="lg:p-36 md:p-52 sm:20 p-8 w-full lg:w-1/2 text-white">
      <h1 class="text-2xl font-semibold mb-4">Login</h1>
        <!-- Username Input -->
        <div class="mb-4">
          <label for="username" class="block text-white">Username</label>
          <input
            type="text"
            name="username"
            class="w-full border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:border-blue-500 text-black"
            autocomplete="off"
          />
        </div>
        <!-- Password Input -->
        <div class="mb-4">
          <label for="password" class="block text-white">Password</label>
          <input
            type="password"
            name="password"
            class="w-full border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:border-blue-500 text-black"
            autocomplete="off"
          />
        </div>
        <!-- Login Button -->
        <button
          class="bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-md py-2 px-4 w-full"
          on:click={handleSubmit}
        >
          Login
        </button>
    </div>
  </div>
